Again

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -470,8 +470,8 @@ jobs:
         #!/bin/bash
         set -e
         adb shell ip addr show
-        adb shell "false && echo \$?" | tr -d '\r' && echo failed false
-        adb shell "true && echo \$?" | tr -d '\r' && echo failed true
+        [ $(adb shell "false && echo \$?" | tr -d '\r') ] && echo failed false
+        [ $(adb shell "true && echo \$?" | tr -d '\r') ] && echo failed true
         export GITHUB_ACTIONS=1
         adb wait-for-device
         while [ -z "$(adb shell getprop sys.boot_completed | tr -d '\r')" ]; do
@@ -483,7 +483,7 @@ jobs:
           adb push "$test" /data/local/tmp/
           adb shell chmod +x /data/local/tmp/$(basename "$test")
           # See
-          adb shell "API_LEVEL=$API_LEVEL /data/local/tmp/$(basename "$test") && echo SUCCESS || echo FAIL" | grep FAIL && any_failures=1
+          [ $(adb shell "API_LEVEL=$API_LEVEL /data/local/tmp/$(basename "$test") && echo \$?" | tr -d '\r') ] && any_failures=1
         done
         echo "Failures: $any_failures"
         exit $any_failures
